/* Capricorn Systems — Product Portfolio product data */
const APPS_DATA = {
  vaultcap: {
    id: 'VaultCap',
    slug: 'vaultcap',
    name: 'VaultCap',
    ver: '4.1.0',
    emoji: '🔐',
    tagline: 'Your life. Encrypted. On your device.',
    pitch: 'A zero-knowledge life operating system for finance, identity, and documents across Pakistan, UK, and UAE — with no server, no account, and no subscription.',
    personality: 'Swiss vault meets command center — precise, calm, authoritative.',
    aesthetic: 'Space Grotesk + IBM Plex Mono · indigo grid · tight 6px corners · calm motion',
    accent: '#5b8dee',
    accent2: '#7b5fff',
    bg: '#070b14',
    url: 'https://shamikhahmed.github.io/VaultCap/',
    pitchUrl: 'https://shamikhahmed.github.io/VaultCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/VaultCap/privacy.html',
    github: 'https://github.com/shamikhahmed/VaultCap',
    modules: '22',
    highlights: ['AES-256-GCM vault', '120+ banks PK/UK/UAE', 'Family vault', 'Zakat engine', 'Smart Import (offline)'],
    vsMarket: 'Not another budget app that sells your data. VaultCap is a private encrypted vault — like 1Password meets Mint, but entirely on-device.',
    audience: 'Multinational families, privacy-conscious professionals, diaspora managing PK + UK finances',
    tech: ['PWA', 'Web Crypto', 'PBKDF2 310k', 'Offline-first', 'Capacitor iOS'],
  },
  pulsecap: {
    id: 'PulseCap',
    slug: 'pulsecap',
    name: 'PulseCap',
    ver: '4.5.1',
    emoji: '💪',
    tagline: 'Train smarter. Recover harder. No cloud.',
    pitch: 'A performance operating system with 300+ exercises, body intelligence, Smart Coach, and recovery science — built for lifters who want Apple-quality UX without a subscription.',
    personality: 'Nike Training Club energy — kinetic, bold, data-driven motion.',
    aesthetic: 'Rajdhani + Sora · electric cyan stripes · angular nav · kinetic stats',
    accent: '#00d5ff',
    accent2: '#6b5fff',
    bg: '#0d0d0f',
    url: 'https://shamikhahmed.github.io/PulseCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PulseCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/PulseCap/privacy.html',
    github: 'https://github.com/shamikhahmed/PulseCap',
    modules: '15+',
    highlights: ['300+ exercises', 'Body map + measurements', 'Smart Coach', 'Recovery readiness', 'PR tracking'],
    vsMarket: 'Not a generic workout logger. PulseCap connects training, recovery, and coaching in one OS — closer to Whoop + Strong, without hardware lock-in.',
    audience: 'Serious lifters, home gym athletes, coaches who want offline reliability',
    tech: ['PWA', 'Canvas viz', 'Rule-based coach', 'localStorage', 'Capacitor iOS'],
  },
  prismcap: {
    id: 'PrismCap',
    slug: 'prismcap',
    name: 'PrismCap',
    ver: '4.0.0',
    emoji: '🎮',
    tagline: '39 games. One phone. Zero Wi‑Fi.',
    pitch: 'A holographic party arcade with 38 pass-and-play games, achievements, daily challenges, and couch multiplayer — no accounts, no ads, no internet required.',
    personality: 'Jackbox meets Apple Arcade — playful, neon, social chaos.',
    aesthetic: 'Audiowide display · neon magenta glass · pill buttons · arcade pulse',
    accent: '#c77dff',
    accent2: '#ff2d78',
    bg: '#0a0014',
    url: 'https://shamikhahmed.github.io/PrismCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PrismCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/PrismCap/privacy.html',
    github: 'https://github.com/shamikhahmed/PrismCap',
    modules: '39 games',
    highlights: ['Pass & Play', 'Truth Bomb & Shadow Protocol', 'Daily challenges', 'XP + achievements', 'QR state transfer'],
    vsMarket: 'Not another mobile game with loot boxes. PrismCap is a living-room OS for parties — like buying 38 board games in one install.',
    audience: 'Families, friend groups, dorm rooms, anyone who wants instant offline fun',
    tech: ['PWA', '38 game engines', 'Haptics', 'Offline audio', 'Capacitor iOS'],
  },
  steadycap: {
    id: 'SteadyCap',
    slug: 'steadycap',
    name: 'SteadyCap',
    ver: '2.0.0',
    emoji: '🧡',
    tagline: 'Recovery is a system. Not a streak.',
    pitch: 'A recovery operating system for habits, medicines, journal triggers, craving forecasts, and a 5-phase SOS — designed with clinical seriousness and human warmth.',
    personality: 'Calm clinical warmth — Headspace meets recovery clinic.',
    aesthetic: 'Fraunces serif · orange/teal warmth · 26px soft cards · recovery calm',
    accent: '#ff6b35',
    accent2: '#2ec4b6',
    bg: '#0f0f12',
    url: 'https://shamikhahmed.github.io/SteadyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/SteadyCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/SteadyCap/privacy.html',
    github: 'https://github.com/shamikhahmed/SteadyCap',
    modules: '8',
    highlights: ['Trigger forecast', '5-phase SOS', 'Medicine tracker', 'Journal triggers', 'Habit milestones'],
    vsMarket: 'Not a generic habit tracker with guilt mechanics. SteadyCap is built for recovery — pattern-aware, private, and SOS-ready when it matters.',
    audience: 'Recovery journeys, structured habit rebuilders, supporters who need discretion',
    tech: ['PWA', 'TriggerEngine', 'Pattern forecast', 'localStorage', 'Capacitor iOS'],
  },
  ledgercap: {
    id: 'LedgerCap',
    slug: 'ledgercap',
    name: 'LedgerCap',
    ver: '2.3.0',
    emoji: '📈',
    tagline: 'Pakistani wealth. One ledger. Your phone.',
    pitch: 'A wealth operating system for PSX stocks, Meezan funds, Zakat, IPO tracking, and net worth — built for Pakistani investors who want Bloomberg clarity without Bloomberg price.',
    personality: 'Terminal-grade finance — Bloomberg meets local brokerage.',
    aesthetic: 'Barlow Condensed + JetBrains Mono · gold terminal bar · 4px sharp grid',
    accent: '#f59e0b',
    accent2: '#0ecb81',
    bg: '#0b0e11',
    url: 'https://shamikhahmed.github.io/LedgerCap/',
    pitchUrl: 'https://shamikhahmed.github.io/LedgerCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/LedgerCap/privacy.html',
    github: 'https://github.com/shamikhahmed/LedgerCap',
    modules: '10',
    highlights: ['PSX holdings', 'Meezan funds', 'Zakat calculator', 'IPO tracker', 'Net worth PKR'],
    vsMarket: 'Not a US-centric portfolio app that ignores PSX. LedgerCap is the wealth OS Pakistan actually needs — local markets, Zakat, zero cloud.',
    audience: 'Pakistani investors, fund holders, anyone tracking PKR net worth privately',
    tech: ['PWA', 'PKR engine', 'Zakat module', 'IndexedDB', 'Capacitor iOS'],
  },
  deeponycap: {
    id: 'DeePonyCap',
    slug: 'deeponycap',
    name: 'DeePonyCap',
    ver: '2.2.0',
    emoji: '🦄',
    tagline: 'Every pony. One stable. Pure joy.',
    pitch: 'A child-safe MLP collection OS with generations G1–G5, wishlists, photo shelves, and bubble stats — playful enough for kids, powerful enough for collectors.',
    personality: 'Toy shelf wonderland — Fisher-Price meets collector catalog.',
    aesthetic: 'Baloo 2 + Nunito · pastel pink bubbles · floating pill nav · bouncy FAB',
    accent: '#ff6b9d',
    accent2: '#c4b5fd',
    bg: '#fff5f8',
    dark: false,
    url: 'https://shamikhahmed.github.io/DeePonyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/DeePonyCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/DeePonyCap/privacy.html',
    github: 'https://github.com/shamikhahmed/DeePonyCap',
    modules: '6',
    highlights: ['G1–G5 catalog', 'Photo shelves', 'Wishlist tiers', 'Achievement bubbles', 'COPPA-safe'],
    vsMarket: 'Not a spreadsheet for collectors. DeePonyCap feels like opening a toy chest — built for a child to use alone, safely, offline.',
    audience: 'MLP collectors, parents, kids cataloguing their stable',
    tech: ['PWA', 'IndexedDB photos', 'COPPA design', 'Offline catalog', 'Capacitor iOS'],
  },
  scentcap: {
    id: 'ScentCap',
    slug: 'scentcap',
    name: 'ScentCap',
    ver: '1.0.0',
    emoji: '💧',
    tagline: 'Your fragrance operating system.',
    pitch: 'A fragrance wardrobe app — catalog bottles, weather-aware daily picks, layering lab, and wear calendar. Offline, no beauty-app accounts.',
    personality: 'Warm perfumery — amber mist, editorial calm.',
    aesthetic: 'Fraunces + DM Sans · amber gold · soft cards · mist gradients',
    accent: '#c9a87c',
    accent2: '#8b6914',
    bg: '#1a1614',
    url: 'https://shamikhahmed.github.io/ScentCap/',
    pitchUrl: 'https://shamikhahmed.github.io/ScentCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/ScentCap/privacy.html',
    github: 'https://github.com/shamikhahmed/ScentCap',
    modules: '8',
    highlights: ['Wardrobe catalog', 'Smart Advisor', 'Layering Lab', 'Wear calendar', 'Offline PWA'],
    vsMarket: 'Not a notes app or cloud beauty profile — ScentCap is a private fragrance OS on your phone.',
    audience: 'Fragrance collectors, office professionals, travelers packing decants',
    tech: ['PWA', 'Rules-based advisor', 'Open-Meteo optional', 'localStorage', 'Capacitor iOS'],
  },
  auracap: {
    id: 'AuraCap',
    slug: 'auracap',
    name: 'AuraCap',
    ver: '5.0.0',
    emoji: '◎',
    tagline: 'Every device. Perfected.',
    pitch: 'An Apple ecosystem organizer — import your app list, score your setup, design layouts and wallpapers. iPhone, iPad, Mac — all offline.',
    personality: 'Glass studio — dark chrome, blue-purple glow, power-user calm.',
    aesthetic: 'SF Pro + JetBrains Mono · glass panels · device frames · command palette',
    accent: '#4f6ef7',
    accent2: '#7b5ea7',
    bg: '#050507',
    url: 'https://shamikhahmed.github.io/AuraCap/',
    pitchUrl: 'https://shamikhahmed.github.io/AuraCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/AuraCap/privacy.html',
    github: 'https://github.com/shamikhahmed/AuraCap',
    modules: '16',
    highlights: ['Digital DNA', 'Aura Score', 'Import flows', 'Design studio', 'Offline PWA'],
    vsMarket: 'Not a screenshot mood board or cloud planner — AuraCap analyzes your real app list locally.',
    audience: 'Multi-device Apple users, customization enthusiasts, productivity power users',
    tech: ['PWA', 'IndexedDB', 'Rules-based designer', 'Shortcuts import', 'Capacitor iOS'],
  },
};

const APPS_LIST = Object.values(APPS_DATA);

const DEVELOPER = {
  name: 'Shamikh Ahmed',
  roles: ['Director, NEWS Logistics', 'Founder, TheSolution360', 'OS Portfolio Builder'],
  location: 'Pakistan · UK · UAE',
  bio: 'I build personal operating systems — not apps that rent your data back to you. Eight production PWAs, one philosophy: your device, your rules, forever.',
  skills: [
    { cat: 'Product', items: ['PWA architecture', 'Offline-first UX', 'Zero-knowledge design', 'App Store / Capacitor'] },
    { cat: 'Engineering', items: ['Vanilla JS', 'Web Crypto', 'IndexedDB', 'Playwright QA', 'Service Workers'] },
    { cat: 'Domains', items: ['FinTech / Vault', 'Fitness science', 'Game design', 'Recovery systems', 'PSX markets'] },
    { cat: 'Enterprise', items: ['Investor demos', 'SECURITY.md truth', 'Seed data UIs', 'TestFlight path'] },
  ],
  links: {
    github: 'https://github.com/shamikhahmed',
    enterprise: './enterprise.html',
  },
};

/** The ONE similarity across all OS apps */
const DEVICE_SOVEREIGNTY = {
  title: 'Device Sovereignty',
  subtitle: 'The one rule every OS app shares',
  points: [
    'Data stays on your device — never sold, never synced to our servers',
    'Works offline after first load — no mandatory account',
    'You own the vault, the workouts, the games, the ledger',
  ],
};
