/* Shamikh Ahmed — OS Portfolio product data */
const APPS_DATA = {
  vaultos: {
    id: 'VaultOS',
    slug: 'vaultos',
    name: 'VaultOS',
    ver: '4.1.0',
    emoji: '🔐',
    tagline: 'Your life. Encrypted. On your device.',
    pitch: 'A zero-knowledge life operating system for finance, identity, and documents across Pakistan, UK, and UAE — with no server, no account, and no subscription.',
    personality: 'Swiss vault meets command center — precise, calm, authoritative.',
    aesthetic: 'IBM Plex + JetBrains Mono · indigo grid · tight 6px corners · calm motion',
    accent: '#5b8dee',
    accent2: '#7b5fff',
    bg: '#070b14',
    url: 'https://shamikhahmed.github.io/VaultOS/',
    pitchUrl: 'https://shamikhahmed.github.io/VaultOS/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/VaultOS/privacy.html',
    github: 'https://github.com/shamikhahmed/VaultOS',
    modules: '22',
    highlights: ['AES-256-GCM vault', '120+ banks PK/UK/UAE', 'Family vault', 'Zakat engine', 'Smart Import (offline)'],
    vsMarket: 'Not another budget app that sells your data. VaultOS is a private encrypted vault — like 1Password meets Mint, but entirely on-device.',
    audience: 'Multinational families, privacy-conscious professionals, diaspora managing PK + UK finances',
    tech: ['PWA', 'Web Crypto', 'PBKDF2 310k', 'Offline-first', 'Capacitor iOS'],
  },
  fitnessos: {
    id: 'FitnessOS',
    slug: 'fitnessos',
    name: 'FitnessOS',
    ver: '4.5.1',
    emoji: '💪',
    tagline: 'Train smarter. Recover harder. No cloud.',
    pitch: 'A performance operating system with 300+ exercises, body intelligence, Smart Coach, and recovery science — built for lifters who want Apple-quality UX without a subscription.',
    personality: 'Nike Training Club energy — kinetic, bold, data-driven motion.',
    aesthetic: 'Barlow Condensed headlines · electric cyan · sharp 10px corners · kinetic nav',
    accent: '#00d5ff',
    accent2: '#6b5fff',
    bg: '#0d0d0f',
    url: 'https://shamikhahmed.github.io/FitnessOS/',
    pitchUrl: 'https://shamikhahmed.github.io/FitnessOS/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/FitnessOS/privacy.html',
    github: 'https://github.com/shamikhahmed/FitnessOS',
    modules: '15+',
    highlights: ['300+ exercises', 'Body map + measurements', 'Smart Coach', 'Recovery readiness', 'PR tracking'],
    vsMarket: 'Not a generic workout logger. FitnessOS connects training, recovery, and coaching in one OS — closer to Whoop + Strong, without hardware lock-in.',
    audience: 'Serious lifters, home gym athletes, coaches who want offline reliability',
    tech: ['PWA', 'Canvas viz', 'Rule-based coach', 'localStorage', 'Capacitor iOS'],
  },
  prismos: {
    id: 'PrismOS',
    slug: 'prismos',
    name: 'PrismOS',
    ver: '4.0.0',
    emoji: '🎮',
    tagline: '38 games. One phone. Zero Wi‑Fi.',
    pitch: 'A holographic party arcade with 38 pass-and-play games, achievements, daily challenges, and couch multiplayer — no accounts, no ads, no internet required.',
    personality: 'Jackbox meets Apple Arcade — playful, neon, social chaos.',
    aesthetic: 'Audiowide display · neon magenta glass · pill buttons · arcade pulse',
    accent: '#c77dff',
    accent2: '#ff2d78',
    bg: '#0a0014',
    url: 'https://shamikhahmed.github.io/PrismOS/',
    pitchUrl: 'https://shamikhahmed.github.io/PrismOS/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/PrismOS/privacy.html',
    github: 'https://github.com/shamikhahmed/PrismOS',
    modules: '38 games',
    highlights: ['Pass & Play', 'Truth Bomb & Shadow Protocol', 'Daily challenges', 'XP + achievements', 'QR state transfer'],
    vsMarket: 'Not another mobile game with loot boxes. PrismOS is a living-room OS for parties — like buying 38 board games in one install.',
    audience: 'Families, friend groups, dorm rooms, anyone who wants instant offline fun',
    tech: ['PWA', '38 game engines', 'Haptics', 'Offline audio', 'Capacitor iOS'],
  },
  disciplineos: {
    id: 'DisciplineOS',
    slug: 'disciplineos',
    name: 'DisciplineOS',
    ver: '2.0.0',
    emoji: '🧡',
    tagline: 'Recovery is a system. Not a streak.',
    pitch: 'A recovery operating system for habits, medicines, journal triggers, craving forecasts, and a 5-phase SOS — designed with clinical seriousness and human warmth.',
    personality: 'Calm clinical warmth — Headspace meets recovery clinic.',
    aesthetic: 'Fraunces serif · orange/teal warmth · 26px soft cards · recovery calm',
    accent: '#ff6b35',
    accent2: '#2ec4b6',
    bg: '#0f0f12',
    url: 'https://shamikhahmed.github.io/DisciplineOS/',
    pitchUrl: 'https://shamikhahmed.github.io/DisciplineOS/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/DisciplineOS/privacy.html',
    github: 'https://github.com/shamikhahmed/DisciplineOS',
    modules: '8',
    highlights: ['Trigger forecast', '5-phase SOS', 'Medicine tracker', 'Journal triggers', 'Habit milestones'],
    vsMarket: 'Not a generic habit tracker with guilt mechanics. DisciplineOS is built for recovery — pattern-aware, private, and SOS-ready when it matters.',
    audience: 'Recovery journeys, structured habit rebuilders, supporters who need discretion',
    tech: ['PWA', 'TriggerEngine', 'Pattern forecast', 'localStorage', 'Capacitor iOS'],
  },
  stundsos: {
    id: 'StundsOS',
    slug: 'stundsos',
    name: 'StundsOS',
    ver: '2.3.0',
    emoji: '📈',
    tagline: 'Pakistani wealth. One ledger. Your phone.',
    pitch: 'A wealth operating system for PSX stocks, Meezan funds, Zakat, IPO tracking, and net worth — built for Pakistani investors who want Bloomberg clarity without Bloomberg price.',
    personality: 'Terminal-grade finance — Bloomberg meets local brokerage.',
    aesthetic: 'Barlow Condensed + JetBrains Mono · gold terminal bar · 4px sharp grid',
    accent: '#f59e0b',
    accent2: '#0ecb81',
    bg: '#0b0e11',
    url: 'https://shamikhahmed.github.io/StundsOS/',
    pitchUrl: 'https://shamikhahmed.github.io/StundsOS/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/StundsOS/privacy.html',
    github: 'https://github.com/shamikhahmed/StundsOS',
    modules: '10',
    highlights: ['PSX holdings', 'Meezan funds', 'Zakat calculator', 'IPO tracker', 'Net worth PKR'],
    vsMarket: 'Not a US-centric portfolio app that ignores PSX. StundsOS is the wealth OS Pakistan actually needs — local markets, Zakat, zero cloud.',
    audience: 'Pakistani investors, fund holders, anyone tracking PKR net worth privately',
    tech: ['PWA', 'PKR engine', 'Zakat module', 'IndexedDB', 'Capacitor iOS'],
  },
  deeponyos: {
    id: 'DeePonyOS',
    slug: 'deeponyos',
    name: 'DeePonyOS',
    ver: '2.2.0',
    emoji: '🦄',
    tagline: 'Every pony. One stable. Pure joy.',
    pitch: 'A child-safe MLP collection OS with generations G1–G5, wishlists, photo shelves, and bubble stats — playful enough for kids, powerful enough for collectors.',
    personality: 'Toy shelf wonderland — Fisher-Price meets collector catalog.',
    aesthetic: 'Baloo 2 + Nunito · pastel pink bubbles · floating pill nav · bouncy FAB',
    accent: '#ff6b9d',
    accent2: '#c4b5fd',
    bg: '#fff5f8',
    dark: false,
    url: 'https://shamikhahmed.github.io/DeePonyOS/',
    pitchUrl: 'https://shamikhahmed.github.io/DeePonyOS/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/DeePonyOS/privacy.html',
    github: 'https://github.com/shamikhahmed/DeePonyOS',
    modules: '6',
    highlights: ['G1–G5 catalog', 'Photo shelves', 'Wishlist tiers', 'Achievement bubbles', 'COPPA-safe'],
    vsMarket: 'Not a spreadsheet for collectors. DeePonyOS feels like opening a toy chest — built for a child to use alone, safely, offline.',
    audience: 'MLP collectors, parents, kids cataloguing their stable',
    tech: ['PWA', 'IndexedDB photos', 'COPPA design', 'Offline catalog', 'Capacitor iOS'],
  },
};

const APPS_LIST = Object.values(APPS_DATA);

const DEVELOPER = {
  name: 'Shamikh Ahmed',
  roles: ['Director, NEWS Logistics', 'Founder, TheSolution360', 'OS Portfolio Builder'],
  location: 'Pakistan · UK · UAE',
  bio: 'I build personal operating systems — not apps that rent your data back to you. Six production PWAs, one philosophy: your device, your rules, forever.',
  skills: [
    { cat: 'Product', items: ['PWA architecture', 'Offline-first UX', 'Zero-knowledge design', 'App Store / Capacitor'] },
    { cat: 'Engineering', items: ['Vanilla JS', 'Web Crypto', 'IndexedDB', 'Playwright QA', 'Service Workers'] },
    { cat: 'Domains', items: ['FinTech / Vault', 'Fitness science', 'Game design', 'Recovery systems', 'PSX markets'] },
    { cat: 'Enterprise', items: ['Investor demos', 'SECURITY.md truth', 'Seed data UIs', 'TestFlight path'] },
  ],
  links: {
    github: 'https://github.com/shamikhahmed',
    enterprise: './enterprise.html',
  },
};

/** The ONE similarity across all OS apps */
const DEVICE_SOVEREIGNTY = {
  title: 'Device Sovereignty',
  subtitle: 'The one rule every OS app shares',
  points: [
    'Data stays on your device — never sold, never synced to our servers',
    'Works offline after first load — no mandatory account',
    'You own the vault, the workouts, the games, the ledger',
  ],
};
