/* GENERATED by scripts/sync-design-system.mjs — DO NOT EDIT.
   Source: shared/design-system/{capricorn-motion.js} */

/* ════════════════════════════════════════════════════════════════
   Capricorn Design System — motion runtime (~1.5 KB, no deps)
   Drives .cap-reveal*, .cap-magnetic, [data-cap-tilt] from motion.css.
   Safe to include on any page; respects prefers-reduced-motion.
   ════════════════════════════════════════════════════════════════ */
(function () {
  'use strict';
  var reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var finePointer = window.matchMedia('(hover: hover) and (pointer: fine)').matches;

  /* Scroll reveals with automatic child stagger */
  var reveals = document.querySelectorAll('.cap-reveal, .cap-reveal-scale, .cap-reveal-lines');
  if (reveals.length) {
    if (reduced || !('IntersectionObserver' in window)) {
      reveals.forEach(function (el) { el.classList.add('is-visible'); });
    } else {
      var io = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          if (!e.isIntersecting) return;
          e.target.classList.add('is-visible');
          io.unobserve(e.target);
        });
      }, { threshold: 0.12, rootMargin: '0px 0px -8% 0px' });
      reveals.forEach(function (el, i) {
        if (!el.style.getPropertyValue('--cap-stagger-i')) {
          var sib = el.parentElement ? Array.prototype.indexOf.call(el.parentElement.children, el) : i;
          el.style.setProperty('--cap-stagger-i', String(sib % 8));
        }
        io.observe(el);
      });
    }
  }

  if (reduced || !finePointer) return;

  /* Magnetic hover — element drifts toward the cursor */
  document.querySelectorAll('.cap-magnetic').forEach(function (el) {
    var strength = parseFloat(el.dataset.capStrength || '0.25');
    el.addEventListener('pointermove', function (ev) {
      var r = el.getBoundingClientRect();
      el.style.setProperty('--cap-mx', ((ev.clientX - r.left - r.width / 2) * strength).toFixed(1));
      el.style.setProperty('--cap-my', ((ev.clientY - r.top - r.height / 2) * strength).toFixed(1));
    });
    el.addEventListener('pointerleave', function () {
      el.style.setProperty('--cap-mx', '0');
      el.style.setProperty('--cap-my', '0');
    });
  });

  /* Pointer tilt — subtle 3D card depth */
  document.querySelectorAll('[data-cap-tilt]').forEach(function (el) {
    var max = parseFloat(el.dataset.capTilt || '6');
    el.classList.add('cap-depth');
    el.addEventListener('pointermove', function (ev) {
      var r = el.getBoundingClientRect();
      var rx = ((ev.clientY - r.top) / r.height - 0.5) * -2 * max;
      var ry = ((ev.clientX - r.left) / r.width - 0.5) * 2 * max;
      el.style.transform = 'perspective(800px) rotateX(' + rx.toFixed(2) + 'deg) rotateY(' + ry.toFixed(2) + 'deg)';
    });
    el.addEventListener('pointerleave', function () { el.style.transform = ''; });
  });
})();
