/* GENERATED by scripts/sync-design-system.mjs — DO NOT EDIT.
   Source: shared/design-system/{capricorn-pitch.js} */

'use strict';
/**
 * Capricorn Pitch — scroll-snap pitch decks with GSAP ScrollTrigger reveals + 3D scene.
 * Auto-boots on full-viewport .slide sections (not #deck presentation mode).
 */
const CapPitch = (() => {
  const reduced = () => window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const g = () => window.gsap;

  function ensureScene() {
    if (document.getElementById('cap-scene') || document.getElementById('deck')) return;
    const c = document.createElement('canvas');
    c.id = 'cap-scene';
    c.className = 'cap-scene-canvas cap-scene-canvas--subtle';
    c.setAttribute('aria-hidden', 'true');
    c.style.cssText = 'position:fixed;inset:0;z-index:0;pointer-events:none;opacity:.22';
    document.body.prepend(c);
    if (window.CapricornScene) CapricornScene.init({ canvas: '#cap-scene', intensity: 0.7 });
  }

  function initScrollReveals() {
    if (reduced() || !g() || !window.ScrollTrigger) return;
    g().registerPlugin(window.ScrollTrigger);

    g().utils.toArray('.reveal, .reveal-left, .reveal-right').forEach((el) => {
      if (el.classList.contains('visible')) return;
      const from = el.classList.contains('reveal-left')
        ? { opacity: 0, x: -48 }
        : el.classList.contains('reveal-right')
          ? { opacity: 0, x: 48 }
          : { opacity: 0, y: 44 };

      g().fromTo(
        el,
        from,
        {
          opacity: 1,
          x: 0,
          y: 0,
          duration: 0.88,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: el,
            start: 'top 86%',
            toggleActions: 'play none none reverse',
          },
        },
      );
    });

    g().utils.toArray('section.slide, .slide').forEach((slide) => {
      g().fromTo(
        slide,
        { opacity: 0.92 },
        {
          opacity: 1,
          duration: 0.6,
          scrollTrigger: {
            trigger: slide,
            start: 'top 75%',
            end: 'bottom 25%',
            toggleActions: 'play none none reverse',
          },
        },
      );
    });
  }

  function enhanceKeyboardScroll(slides) {
    if (!g()) return;
    let currentSlide = 0;

    function syncIdx() {
      slides.forEach((s, i) => {
        if (Math.abs(s.getBoundingClientRect().top) < innerHeight / 2) currentSlide = i;
      });
    }

    addEventListener('scroll', syncIdx, { passive: true });

    document.addEventListener('keydown', (e) => {
      syncIdx();
      if (e.key === 'ArrowDown' || e.key === 'PageDown') {
        e.preventDefault();
        if (currentSlide < slides.length - 1) slides[currentSlide + 1].scrollIntoView({ behavior: 'smooth' });
      }
      if (e.key === 'ArrowUp' || e.key === 'PageUp') {
        e.preventDefault();
        if (currentSlide > 0) slides[currentSlide - 1].scrollIntoView({ behavior: 'smooth' });
      }
    });
  }

  function init() {
    if (document.getElementById('deck')) return null;

    const slides = [...document.querySelectorAll('section.slide, body > .slide')];
    if (!slides.length) return null;

    ensureScene();
    initScrollReveals();
    enhanceKeyboardScroll(slides);

    const bar = document.createElement('div');
    bar.className = 'cap-scroll-progress';
    bar.setAttribute('aria-hidden', 'true');
    if (!document.querySelector('.cap-scroll-progress')) document.body.appendChild(bar);

    if (g() && window.ScrollTrigger) {
      g().to(bar, {
        scaleX: 1,
        ease: 'none',
        scrollTrigger: {
          trigger: document.body,
          start: 'top top',
          end: 'bottom bottom',
          scrub: 0.2,
          onUpdate: (self) => { bar.style.transform = `scaleX(${self.progress})`; },
        },
      });
    }

    return { slides };
  }

  return { init };
})();

window.CapPitch = CapPitch;

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => CapPitch.init());
} else {
  CapPitch.init();
}
