/* GENERATED by scripts/sync-design-system.mjs — DO NOT EDIT.
   Source: shared/design-system/{capricorn-scene.js} */

'use strict';
/**
 * Capricorn Scene — interactive 3D particle field (zero deps)
 * Apple/Samsung-style ambient WebGL with pointer parallax, scroll depth,
 * tap ripples, and device-orientation on mobile. Falls back to Canvas2D.
 */
const CapricornScene = (() => {
  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const lowPower = navigator.connection && navigator.connection.saveData;

  function parseAccent() {
    const raw = getComputedStyle(document.documentElement).getPropertyValue('--cap-accent').trim();
    if (raw.startsWith('#') && raw.length >= 7) {
      return [
        parseInt(raw.slice(1, 3), 16),
        parseInt(raw.slice(3, 5), 16),
        parseInt(raw.slice(5, 7), 16),
      ];
    }
    return [201, 162, 39];
  }

  function ensureCanvas(id, className) {
    let c = document.getElementById(id);
    if (c) return c;
    c = document.createElement('canvas');
    c.id = id;
    c.className = className || 'cap-scene-canvas cap-scene-canvas--subtle';
    c.setAttribute('aria-hidden', 'true');
    document.body.prepend(c);
    return c;
  }

  function initCanvas2D(canvas, opts) {
    const ctx = canvas.getContext('2d', { alpha: true });
    if (!ctx) return null;

    let W = 0, H = 0, accent = parseAccent();
    const mobile = innerWidth < 640;
    const count = mobile ? 48 : 90;
    const orbs = [];
    let px = 0, py = 0, tx = 0, ty = 0, scrollP = 0;
    let running = true, raf = 0, last = 0;

    function resize() {
      W = canvas.width = innerWidth * Math.min(devicePixelRatio, 2);
      H = canvas.height = innerHeight * Math.min(devicePixelRatio, 2);
      canvas.style.width = innerWidth + 'px';
      canvas.style.height = innerHeight + 'px';
    }

    function seed() {
      orbs.length = 0;
      for (let i = 0; i < count; i++) {
        orbs.push({
          x: Math.random() * W,
          y: Math.random() * H,
          z: Math.random(),
          r: (mobile ? 90 : 130) + Math.random() * 100,
          vx: (Math.random() - 0.5) * 0.15,
          vy: (Math.random() - 0.5) * 0.15,
          ph: Math.random() * Math.PI * 2,
        });
      }
    }

    function draw(ts) {
      if (!running) return;
      raf = requestAnimationFrame(draw);
      if (ts - last < (mobile ? 40 : 28)) return;
      last = ts;
      px += (tx - px) * 0.05;
      py += (ty - py) * 0.05;
      ctx.clearRect(0, 0, W, H);
      const t = ts * 0.001;
      orbs.forEach((o) => {
        const depth = 0.35 + o.z * 0.65;
        const pulse = 1 + Math.sin(t * 1.2 + o.ph) * 0.06;
        const r = o.r * depth * pulse * (opts.intensity || 1);
        const ox = (px * 40 * depth) + scrollP * 20 * depth;
        const oy = (py * 30 * depth) - scrollP * 35;
        const g = ctx.createRadialGradient(o.x + ox, o.y + oy, 0, o.x + ox, o.y + oy, r);
        const a = (0.025 + o.z * 0.035) * (opts.intensity || 1);
        g.addColorStop(0, 'rgba(' + accent[0] + ',' + accent[1] + ',' + accent[2] + ',' + a + ')');
        g.addColorStop(1, 'rgba(' + accent[0] + ',' + accent[1] + ',' + accent[2] + ',0)');
        ctx.fillStyle = g;
        ctx.beginPath();
        ctx.arc(o.x + ox, o.y + oy, r, 0, Math.PI * 2);
        ctx.fill();
        o.x += o.vx * depth;
        o.y += o.vy * depth;
        if (o.x < -r) o.x = W + r;
        if (o.x > W + r) o.x = -r;
        if (o.y < -r) o.y = H + r;
        if (o.y > H + r) o.y = -r;
      });
    }

    resize();
    seed();
    window.addEventListener('resize', () => { resize(); seed(); }, { passive: true });
    window.addEventListener('pointermove', (e) => {
      tx = (e.clientX / innerWidth - 0.5) * 2;
      ty = (e.clientY / innerHeight - 0.5) * 2;
    }, { passive: true });
    window.addEventListener('scroll', () => {
      const max = Math.max(document.documentElement.scrollHeight - innerHeight, 1);
      scrollP = window.scrollY / max;
    }, { passive: true });
    document.addEventListener('visibilitychange', () => {
      running = !document.hidden;
      if (running) raf = requestAnimationFrame(draw);
    });
    raf = requestAnimationFrame(draw);
    return { destroy: () => { running = false; cancelAnimationFrame(raf); } };
  }

  function initWebGL(canvas, opts) {
    const gl = canvas.getContext('webgl2', { alpha: true, antialias: false, powerPreference: 'low-power' })
      || canvas.getContext('webgl', { alpha: true, antialias: false, powerPreference: 'low-power' });
    if (!gl) return null;

    const mobile = innerWidth < 640;
    const N = mobile ? 1200 : 2200;
    const accent = parseAccent();
    const positions = new Float32Array(N * 3);
    const scales = new Float32Array(N);
    const seeds = new Float32Array(N);

    for (let i = 0; i < N; i++) {
      const arm = i % 3;
      const r = Math.pow(Math.random(), 0.55) * 5.5;
      const spin = r * 0.9;
      const angle = (arm / 3) * Math.PI * 2 + spin + (Math.random() - 0.5) * 0.5;
      positions[i * 3] = Math.cos(angle) * r;
      positions[i * 3 + 1] = (Math.random() - 0.5) * (0.4 + (5.5 - r) * 0.12);
      positions[i * 3 + 2] = Math.sin(angle) * r;
      scales[i] = 0.4 + Math.random() * 1.4;
      seeds[i] = Math.random() * 100;
    }

    const vs = `
      attribute vec3 aPos;
      attribute float aScale;
      attribute float aSeed;
      uniform float uTime;
      uniform float uScroll;
      uniform vec2 uPointer;
      uniform float uPixelRatio;
      uniform float uSize;
      uniform mat4 uProj;
      uniform mat4 uMv;
      varying float vTw;
      void main() {
        vec3 p = aPos;
        float rot = uTime * 0.04 + uScroll * 1.4;
        float c = cos(rot); float s = sin(rot);
        p.xz = mat2(c, -s, s, c) * p.xz;
        p.x += uPointer.x * (0.35 + aScale * 0.15);
        p.y -= uScroll * 0.8 + uPointer.y * 0.25;
        vec4 mv = uMv * vec4(p, 1.0);
        gl_Position = uProj * mv;
        gl_PointSize = uSize * aScale * uPixelRatio / max(0.1, -mv.z);
        vTw = 0.65 + 0.35 * sin(uTime * 1.5 + aSeed);
      }`;
    const fs = `
      precision mediump float;
      uniform vec3 uAccent;
      varying float vTw;
      void main() {
        float d = smoothstep(0.5, 0.05, length(gl_PointCoord - 0.5));
        gl_FragColor = vec4(uAccent, d * vTw * 0.55);
      }`;

    function compile(type, src) {
      const sh = gl.createShader(type);
      gl.shaderSource(sh, src);
      gl.compileShader(sh);
      if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) return null;
      return sh;
    }

    const prog = gl.createProgram();
    const vsh = compile(gl.VERTEX_SHADER, vs);
    const fsh = compile(gl.FRAGMENT_SHADER, fs);
    if (!vsh || !fsh) return null;
    gl.attachShader(prog, vsh);
    gl.attachShader(prog, fsh);
    gl.linkProgram(prog);
    if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) return null;

    const buf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(gl.ARRAY_BUFFER, positions, gl.STATIC_DRAW);
    const scaleBuf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, scaleBuf);
    gl.bufferData(gl.ARRAY_BUFFER, scales, gl.STATIC_DRAW);
    const seedBuf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, seedBuf);
    gl.bufferData(gl.ARRAY_BUFFER, seeds, gl.STATIC_DRAW);

    gl.enable(gl.BLEND);
    gl.blendFunc(gl.SRC_ALPHA, gl.ONE);
    gl.clearColor(0, 0, 0, 0);

    let W = 0, H = 0, px = 0, py = 0, tx = 0, ty = 0, scrollP = 0;
    let running = true, raf = 0, t0 = performance.now();

    function resize() {
      W = innerWidth;
      H = innerHeight;
      canvas.width = W * Math.min(devicePixelRatio, 2);
      canvas.height = H * Math.min(devicePixelRatio, 2);
      canvas.style.width = W + 'px';
      canvas.style.height = H + 'px';
      gl.viewport(0, 0, canvas.width, canvas.height);
    }

    function draw(now) {
      if (!running) return;
      raf = requestAnimationFrame(draw);
      const t = (now - t0) * 0.001;
      px += (tx - px) * 0.06;
      py += (ty - py) * 0.06;
      gl.clear(gl.COLOR_BUFFER_BIT);
      gl.useProgram(prog);

      const aPos = gl.getAttribLocation(prog, 'aPos');
      gl.bindBuffer(gl.ARRAY_BUFFER, buf);
      gl.enableVertexAttribArray(aPos);
      gl.vertexAttribPointer(aPos, 3, gl.FLOAT, false, 0, 0);

      const aScale = gl.getAttribLocation(prog, 'aScale');
      gl.bindBuffer(gl.ARRAY_BUFFER, scaleBuf);
      gl.enableVertexAttribArray(aScale);
      gl.vertexAttribPointer(aScale, 1, gl.FLOAT, false, 0, 0);

      const aSeed = gl.getAttribLocation(prog, 'aSeed');
      gl.bindBuffer(gl.ARRAY_BUFFER, seedBuf);
      gl.enableVertexAttribArray(aSeed);
      gl.vertexAttribPointer(aSeed, 1, gl.FLOAT, false, 0, 0);

      gl.uniform1f(gl.getUniformLocation(prog, 'uTime'), t);
      gl.uniform1f(gl.getUniformLocation(prog, 'uScroll'), scrollP);
      gl.uniform2f(gl.getUniformLocation(prog, 'uPointer'), px, py);
      gl.uniform1f(gl.getUniformLocation(prog, 'uPixelRatio'), Math.min(devicePixelRatio, 2));
      gl.uniform1f(gl.getUniformLocation(prog, 'uSize'), mobile ? 22 : 28);
      gl.uniform3f(
        gl.getUniformLocation(prog, 'uAccent'),
        accent[0] / 255,
        accent[1] / 255,
        accent[2] / 255,
      );

      const aspect = W / H;
      const proj = perspective(58 * Math.PI / 180, aspect, 0.1, 60);
      const view = lookAt([px * 0.6, 0.4 - scrollP * 1.2 - py * 0.3, 7 + scrollP * 2.5], [0, 0, 0], [0, 1, 0]);
      const model = identity();
      gl.uniformMatrix4fv(gl.getUniformLocation(prog, 'uProj'), false, proj);
      gl.uniformMatrix4fv(gl.getUniformLocation(prog, 'uMv'), false, view);
      gl.drawArrays(gl.POINTS, 0, N);
    }

    resize();
    window.addEventListener('resize', resize, { passive: true });
    window.addEventListener('pointermove', (e) => {
      tx = (e.clientX / innerWidth - 0.5) * 2;
      ty = (e.clientY / innerHeight - 0.5) * 2;
    }, { passive: true });
    window.addEventListener('scroll', () => {
      const max = Math.max(document.documentElement.scrollHeight - innerHeight, 1);
      scrollP = window.scrollY / max;
    }, { passive: true });
    if (window.DeviceOrientationEvent) {
      window.addEventListener('deviceorientation', (e) => {
        if (e.beta == null || e.gamma == null) return;
        tx = Math.max(-1, Math.min(1, (e.gamma || 0) / 35));
        ty = Math.max(-1, Math.min(1, ((e.beta || 0) - 45) / 35));
      }, { passive: true });
    }
    document.addEventListener('visibilitychange', () => {
      running = !document.hidden;
      if (running) { t0 = performance.now(); raf = requestAnimationFrame(draw); }
    });
    raf = requestAnimationFrame(draw);
    return { destroy: () => { running = false; cancelAnimationFrame(raf); } };
  }

  /* Minimal mat4 helpers */
  function identity() {
    const m = new Float32Array(16);
    m[0] = m[5] = m[10] = m[15] = 1;
    return m;
  }
  function perspective(fov, aspect, near, far) {
    const f = 1 / Math.tan(fov / 2);
    const m = identity();
    m[0] = f / aspect;
    m[5] = f;
    m[10] = (far + near) / (near - far);
    m[11] = -1;
    m[14] = (2 * far * near) / (near - far);
    m[15] = 0;
    return m;
  }
  function lookAt(eye, center, up) {
    const z0 = eye[0] - center[0], z1 = eye[1] - center[1], z2 = eye[2] - center[2];
    let len = Math.hypot(z0, z1, z2) || 1;
    const zx = z0 / len, zy = z1 / len, zz = z2 / len;
    const x0 = up[1] * zz - up[2] * zy, x1 = up[2] * zx - up[0] * zz, x2 = up[0] * zy - up[1] * zx;
    len = Math.hypot(x0, x1, x2) || 1;
    const xx = x0 / len, xy = x1 / len, xz = x2 / len;
    const yx = zy * xz - zz * xy, yy = zz * xx - zx * xz, yz = zx * xy - zy * xx;
    const m = identity();
    m[0] = xx; m[1] = yx; m[2] = zx;
    m[4] = xy; m[5] = yy; m[6] = zy;
    m[8] = xz; m[9] = yz; m[10] = zz;
    m[12] = -(xx * eye[0] + xy * eye[1] + xz * eye[2]);
    m[13] = -(yx * eye[0] + yy * eye[1] + yz * eye[2]);
    m[14] = -(zx * eye[0] + zy * eye[1] + zz * eye[2]);
    return m;
  }
  function multiply(a, b) {
    const o = new Float32Array(16);
    for (let i = 0; i < 4; i++) {
      for (let j = 0; j < 4; j++) {
        o[i + j * 4] =
          a[i] * b[j * 4] + a[i + 4] * b[j * 4 + 1] + a[i + 8] * b[j * 4 + 2] + a[i + 12] * b[j * 4 + 3];
      }
    }
    return o;
  }

  function init(opts) {
    opts = opts || {};
    if (reduced || lowPower || opts.disabled) return null;
    const canvas = opts.canvas
      ? (typeof opts.canvas === 'string' ? document.querySelector(opts.canvas) : opts.canvas)
      : ensureCanvas(opts.id || 'cap-scene', opts.className);
    if (!canvas) return null;
    document.body.classList.add('cap-has-scene');
    const prefer2d = opts.mode === '2d' || mobileLow();
    const engine = prefer2d ? initCanvas2D(canvas, opts) : (initWebGL(canvas, opts) || initCanvas2D(canvas, opts));
    return engine;
  }

  function mobileLow() {
    return innerWidth < 400 || (navigator.hardwareConcurrency && navigator.hardwareConcurrency <= 4);
  }

  return { init, parseAccent };
})();

if (typeof window !== 'undefined') window.CapricornScene = CapricornScene;
