/* GENERATED by scripts/sync-design-system.mjs — DO NOT EDIT.
   Source: shared/design-system/{capricorn-deck.js} */

'use strict';
/**
 * Capricorn Deck — GSAP 3 pitch/presentation slide engine with 3D transitions.
 * Auto-boots on #deck or [data-cap-deck]. Upgrades mist-canvas → CapricornScene.
 */
const CapDeck = (() => {
  const reduced = () => window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const g = () => window.gsap;

  function init(opts = {}) {
    const deck = document.getElementById('deck') || document.querySelector('[data-cap-deck]');
    if (!deck) return null;

    const slides = [...deck.querySelectorAll('.slide')];
    if (!slides.length) return null;

    const progress = document.getElementById('progress');
    const counter = document.getElementById('counter');
    const arrowL = document.getElementById('arrow-left');
    const arrowR = document.getElementById('arrow-right');
    const fsBtn = document.getElementById('fullscreen-btn');

    let idx = 0;
    const total = slides.length;
    let animating = false;

    if (window.CapricornScene) {
      const canvas = document.getElementById('cap-scene') || document.getElementById('mist-canvas');
      if (canvas) {
        canvas.id = 'cap-scene';
        canvas.classList.add('cap-scene-canvas', 'cap-scene-canvas--subtle');
        CapricornScene.init({ canvas: '#cap-scene', intensity: 0.85, ...(opts.sceneOpts || {}) });
      }
    }

    function updateUI() {
      if (progress) progress.style.width = ((idx + 1) / total * 100) + '%';
      if (counter) counter.textContent = (idx + 1) + ' / ' + total;
    }

    function animateSlideContent(slide, enter) {
      if (!slide || reduced() || !g()) return;
      const parts = slide.querySelectorAll('.a1, .a2, .a3, .a4, .a5, [data-cap-slide-part]');
      if (!parts.length) return;
      if (enter) {
        g().fromTo(
          parts,
          { opacity: 0, y: 36, rotateX: 8, transformPerspective: 900 },
          { opacity: 1, y: 0, rotateX: 0, duration: 0.72, stagger: 0.09, ease: 'power3.out' },
        );
      }
    }

    function show(nextIdx, direction) {
      nextIdx = Math.max(0, Math.min(total - 1, nextIdx));
      if (nextIdx === idx || animating) return;
      const prev = slides[idx];
      const next = slides[nextIdx];
      const dir = direction != null ? direction : (nextIdx > idx ? 1 : -1);
      idx = nextIdx;

      if (reduced() || !g()) {
        slides.forEach((s, j) => s.classList.toggle('active', j === idx));
        updateUI();
        return;
      }

      animating = true;
      slides.forEach((s) => s.classList.remove('active'));

      g().set(next, { opacity: 0, x: dir * 80, rotateY: dir * -6, transformPerspective: 1200, pointerEvents: 'none' });
      next.classList.add('active');

      const tl = g().timeline({
        defaults: { ease: 'power3.inOut' },
        onComplete: () => {
          animating = false;
          next.style.pointerEvents = '';
          g().set(next, { clearProps: 'transform' });
          if (prev && prev !== next) {
            prev.classList.remove('active');
            g().set(prev, { clearProps: 'all' });
          }
          animateSlideContent(next, true);
        },
      });

      if (prev && prev !== next) {
        tl.to(prev, { opacity: 0, x: dir * -60, rotateY: dir * 4, duration: 0.42 }, 0);
      }
      tl.to(next, { opacity: 1, x: 0, rotateY: 0, duration: 0.52 }, 0.06);
      updateUI();
    }

    function next() { show(idx + 1, 1); }
    function prev() { show(idx - 1, -1); }

    document.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowRight' || e.key === 'PageDown' || e.key === ' ') { e.preventDefault(); next(); }
      if (e.key === 'ArrowLeft' || e.key === 'PageUp') prev();
      if (e.key === 'Home') show(0, -1);
      if (e.key === 'End') show(total - 1, 1);
    });

    let tx = 0;
    document.addEventListener('touchstart', (e) => { tx = e.touches[0].clientX; }, { passive: true });
    document.addEventListener('touchend', (e) => {
      const dx = tx - e.changedTouches[0].clientX;
      if (Math.abs(dx) > 50) { if (dx > 0) next(); else prev(); }
    }, { passive: true });

    if (arrowL) arrowL.addEventListener('click', prev);
    if (arrowR) arrowR.addEventListener('click', next);
    if (fsBtn) {
      fsBtn.addEventListener('click', () => {
        if (!document.fullscreenElement) document.documentElement.requestFullscreen?.();
        else document.exitFullscreen?.();
      });
    }

    slides.forEach((s, j) => s.classList.toggle('active', j === 0));
    updateUI();
    animateSlideContent(slides[0], true);

    return { show, next, prev, get index() { return idx; } };
  }

  return { init };
})();

window.CapDeck = CapDeck;

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => CapDeck.init());
} else {
  CapDeck.init();
}
