/* Capricorn Systems — product catalog */
function shotPaths(slug, n = 8) {
  return Array.from({ length: n }, (_, i) =>
    i === 0 ? `assets/screenshots/${slug}.png` : `assets/screenshots/${slug}-${i + 1}.png`
  );
}
function deviceShotPaths(slug) {
  return {
    phone: `assets/screenshots/${slug}-2.png`,
    ipad: `assets/screenshots/${slug}-ipad.png`,
    mac: `assets/screenshots/${slug}-mac.png`,
  };
}

const CAPRICORN = {
  name: 'Capricorn Systems',
  tagline: 'Software that lives on your device — not in our cloud.',
  sub: 'Premium personal software for finance, health, play, recovery, wealth, and life.',
};

const PRODUCTS = {
  vaultcap: {
    id: 'VaultCap',
    slug: 'vaultcap',
    legacySlug: 'vaultos',
    name: 'VaultCap',
    category: 'Finance & Identity',
    ver: '4.1.0',
    symbol: '◆',
    tagline: 'Your encrypted life vault.',
    pitch: 'VaultCap is a zero-knowledge life operating system for finance, identity, and documents — built for multinational families who refuse to rent their privacy from a cloud.',
    hook: 'Bank-grade encryption. No server. No account. No subscription drama.',
    nameStory: 'Cap is short for Capricorn — our constellation. Vault is what it protects: your encrypted life in one place, not scattered across cloud apps.',
    accent: '#5b8dee',
    accent2: '#3d5a9e',
    bg: '#070b14',
    url: 'https://shamikhahmed.github.io/VaultCap/',
    pitchUrl: 'https://shamikhahmed.github.io/VaultCap/pitch.html',
    presentationUrl: 'https://shamikhahmed.github.io/VaultCap/presentation.html',
    privacyUrl: 'https://shamikhahmed.github.io/VaultCap/privacy.html',
    github: 'https://github.com/shamikhahmed/VaultCap',
    problems: [
      'Budget apps want your bank logins and sell insight graphs back to advertisers.',
      'Password managers and finance tools live in separate silos — and both phone home.',
      'Diaspora families juggle PK, UK, and UAE money with no single private ledger.',
    ],
    promise: 'One vault on your phone: net worth, documents, family profiles, Zakat, and 120+ banks — encrypted before it ever touches storage.',
    features: [
      { t: 'AES-256-GCM vault', d: 'Military-grade encryption with PBKDF2 310k iterations. Your PIN never leaves the device.' },
      { t: '120+ banks', d: 'Pakistan, UK, and UAE institutions with smart import — offline parsing, no Plaid dependency.' },
      { t: 'Family vault', d: 'Separate profiles with guided demo, personal default, and premium recovery you control.' },
      { t: 'Zakat engine', d: 'Islamic wealth obligations calculated from your real holdings — private, auditable, on-device.' },
      { t: 'Smart Import', d: 'Drop statements and screenshots; VaultCap structures them without uploading anywhere.' },
      { t: 'Swiss-vault UX', d: 'IBM Plex Mono numerics, indigo grid chrome — calm authority, not fintech neon.' },
    ],
    vs: [
      { name: 'Mint / YNAB', note: 'Cloud-first, account-required, data is the product.' },
      { name: '1Password', note: 'Secrets only — no net worth, Zakat, or family finance OS.' },
    ],
    personas: ['Privacy-conscious professionals', 'Multinational families', 'Diaspora managing PK + UK finances'],
    faqs: [
      { q: 'Does VaultCap need the internet?', a: 'After first load it runs offline. No mandatory sync or account.' },
      { q: 'Can you see my data?', a: 'No. Zero-knowledge design — encryption happens on your device.' },
      { q: 'How do I install?', a: 'Open the app in Safari/Chrome → Share → Add to Home Screen for a full-screen vault.' },
    ],
    highlights: ['AES-256-GCM', '120+ banks', 'Family vault', 'Zakat engine', 'Smart Import'],
    screenshot: 'assets/screenshots/vaultcap.png',
    screenshots: shotPaths('vaultcap'),
    devices: deviceShotPaths('vaultcap'),
    screenshotAlts: [
      'VaultCap marketing landing page',
      'VaultCap unlocked app shell',
      'VaultCap finance dashboard',
      'VaultCap Family Vault overview',
      'VaultCap bank accounts',
      'VaultCap documents vault',
      'VaultCap Zakat calculator',
      'VaultCap investments portfolio',
    ],
    ux: [{'step': '01', 'icon': '🌐', 'title': 'Open VaultCap', 'desc': 'Launch in Safari or Chrome — no account wall before you see anything.'}, {'step': '02', 'icon': '📲', 'title': 'Add to Home Screen', 'desc': 'Share → Add to Home Screen for a full-screen vault with your PIN.'}, {'step': '03', 'icon': '🔐', 'title': 'Unlock locally', 'desc': 'Your PIN decrypts data on-device. Nothing is sent to Capricorn servers.'}, {'step': '04', 'icon': '📊', 'title': 'Run your life OS', 'desc': 'Net worth, banks, documents, Zakat — daily finance without cloud sync.'}],
  },
  pulsecap: {
    id: 'PulseCap',
    slug: 'pulsecap',
    legacySlug: 'fitnessos',
    name: 'PulseCap',
    category: 'Performance',
    symbol: '◇',
    tagline: 'Train smarter. Recover harder.',
    pitch: 'PulseCap is a performance operating system with 300+ exercises, body intelligence, Smart Coach, and recovery science — for lifters who want Whoop-grade insight without a hardware lock-in.',
    hook: 'Your pulse, your PRs, your program — kinetic, offline, yours.',
    nameStory: 'Pulse is the rhythm of training and recovery — the heartbeat of performance. Cap ties it to Capricorn: one company, your pulse on your device.',
    accent: '#00f2ff',
    accent2: '#0e7bff',
    bg: '#0a0a0f',
    url: 'https://shamikhahmed.github.io/PulseCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PulseCap/pitch.html',
    presentationUrl: 'https://shamikhahmed.github.io/PulseCap/presentation.html',
    privacyUrl: 'https://shamikhahmed.github.io/PulseCap/privacy.html',
    github: 'https://github.com/shamikhahmed/PulseCap',
    problems: [
      'Workout apps nag you to subscribe before you can log a single set.',
      'Training and recovery live in different apps that never talk — unless you pay for both.',
      'Cloud fitness products leak habits, locations, and body data you never agreed to share.',
    ],
    promise: 'One kinetic dashboard: training, body map, readiness, PRs, and rule-based Smart Coach — no cloud, no wearable tax.',
    features: [
      { t: '300+ exercises', d: 'Full library with muscle mapping and session logging built for serious training.' },
      { t: 'Body map', d: 'Measurements and visual body intelligence — track composition changes privately.' },
      { t: 'Smart Coach', d: 'Offline rule engine that adapts volume and recovery cues from your actual history.' },
      { t: 'Recovery readiness', d: 'Readiness signals without selling your sleep to a subscription dashboard.' },
      { t: 'PR tracking', d: 'Tabular numerics, angular chrome — every rep counted with athletic precision.' },
      { t: 'Kinetic identity', d: 'Rajdhani + Sora, electric cyan stripes — feels like a training lab, not a logger.' },
    ],
    vs: [
      { name: 'Strong / Hevy', note: 'Great loggers — but cloud accounts and no recovery OS layer.' },
      { name: 'Whoop', note: 'Hardware subscription — PulseCap is software sovereignty on your phone.' },
    ],
    personas: ['Serious lifters', 'Home gym athletes', 'Coaches who need offline reliability'],
    faqs: [
      { q: 'Do I need a wearable?', a: 'No. PulseCap works from your training data and manual inputs.' },
      { q: 'Works offline?', a: 'Yes — full PWA after first load.' },
      { q: 'Install tip', a: 'Add to Home Screen on iPhone for the best full-screen training experience.' },
    ],
    highlights: ['300+ exercises', 'Body map', 'Smart Coach', 'Recovery', 'PR tracking'],
    screenshot: 'assets/screenshots/pulsecap.png',
    screenshots: shotPaths('pulsecap'),
    devices: deviceShotPaths('pulsecap'),
    screenshotAlts: [
      'PulseCap kinetic training landing',
      'PulseCap dashboard home screen',
      'PulseCap training dashboard',
      'PulseCap workout logging',
      'PulseCap nutrition tracking',
      'PulseCap recovery readiness',
      'PulseCap body map intelligence',
      'PulseCap progress analytics',
    ],
    ux: [{'step': '01', 'icon': '⚡', 'title': 'Launch PulseCap', 'desc': 'Open the kinetic training hub — Smart Coach loads offline after first visit.'}, {'step': '02', 'icon': '📲', 'title': 'Install to lock screen', 'desc': 'Add to Home Screen for gym-ready full-screen logging.'}, {'step': '03', 'icon': '🏋️', 'title': 'Log your session', 'desc': '300+ exercises, body map, PRs — all stored on your phone.'}, {'step': '04', 'icon': '💤', 'title': 'Track recovery', 'desc': 'Readiness and recovery cues from your history, not a wearable subscription.'}],
  },
  prismcap: {
    id: 'PrismCap',
    slug: 'prismcap',
    legacySlug: 'prismos',
    name: 'PrismCap',
    category: 'Play',
    symbol: '✦',
    tagline: '38 games. One phone. Zero Wi‑Fi.',
    pitch: 'PrismCap is a holographic party arcade — pass-and-play games, achievements, daily challenges, and couch multiplayer with no accounts, no ads, and no internet required.',
    hook: 'The living room becomes an arcade. Pass the phone, not your data.',
    nameStory: 'A prism splits one beam into many colors — one phone, dozens of games. Cap marks it as part of the Capricorn family of offline-first apps.',
    accent: '#c77dff',
    accent2: '#ff2d78',
    bg: '#0a0014',
    url: 'https://shamikhahmed.github.io/PrismCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PrismCap/pitch.html',
    presentationUrl: 'https://shamikhahmed.github.io/PrismCap/presentation.html',
    privacyUrl: 'https://shamikhahmed.github.io/PrismCap/privacy.html',
    github: 'https://github.com/shamikhahmed/PrismCap',
    problems: [
      'Mobile games demand accounts, loot boxes, and constant connectivity.',
      'Board game nights need setup, pieces, and rules nobody remembers.',
      'Party apps harvest contacts and microphone data for "social features."',
    ],
    promise: 'Install once — 38 engineered games, XP, achievements, and pass-and-play chaos that works in airplane mode.',
    features: [
      { t: '38 game engines', d: 'Deduction, reflex, strategy, party — each with its own drama and haptics.' },
      { t: 'Pass & Play', d: 'Built for the couch: pass the device, reveal roles, betray friends — privately.' },
      { t: 'Daily challenges', d: 'Fresh goals without server pings or push-notification spam.' },
      { t: 'XP + achievements', d: 'Progress stays on your device — your arcade, your legend.' },
      { t: 'QR state transfer', d: 'Move sessions between phones without cloud accounts.' },
      { t: 'Neon arcade chrome', d: 'Audiowide display, magenta glass — Jackbox energy, Apple polish.' },
    ],
    vs: [
      { name: 'Jackbox', note: 'Paid packs + TV setup — PrismCap is 38 games in one phone install.' },
      { name: 'App Store party games', note: 'Ads, accounts, and data harvesting — PrismCap is offline-first.' },
    ],
    personas: ['Families', 'Friend groups', 'Dorm rooms', 'Anyone who wants instant offline fun'],
    faqs: [
      { q: 'Internet required?', a: 'No — after first load, PrismCap is fully offline.' },
      { q: 'How many players?', a: 'Most games support pass-and-play groups; check each game card.' },
      { q: 'Kids safe?', a: 'No accounts, no chat servers, no ads — local play only.' },
    ],
    highlights: ['38 games', 'Pass & Play', 'Daily challenges', 'XP system', 'Offline audio'],
    screenshot: 'assets/screenshots/prismcap.png',
    screenshots: shotPaths('prismcap'),
    devices: deviceShotPaths('prismcap'),
    screenshotAlts: [
      'PrismCap neon arcade landing',
      'PrismCap party game hub',
      'PrismCap home screen',
      'PrismCap arcade game browser',
      'PrismCap player dashboard',
      'PrismCap profile and achievements',
      'PrismCap game selection grid',
      'PrismCap couch multiplayer hub',
    ],
    ux: [{'step': '01', 'icon': '🎮', 'title': 'Open the arcade', 'desc': '38 games load once — then the couch is your LAN party.'}, {'step': '02', 'icon': '📲', 'title': 'Pin to home screen', 'desc': 'Full-screen neon chrome without App Store friction.'}, {'step': '03', 'icon': '👥', 'title': 'Pass & play', 'desc': 'Hand the phone around — roles, betrayals, and scores stay local.'}, {'step': '04', 'icon': '✈️', 'title': 'Play offline', 'desc': 'Airplane mode works. No accounts, no ads, no server pings.'}],
  },
  steadycap: {
    id: 'SteadyCap',
    slug: 'steadycap',
    legacySlug: 'disciplineos',
    name: 'SteadyCap',
    category: 'Recovery',
    symbol: '○',
    tagline: 'Recovery is a system. Not a streak.',
    pitch: 'SteadyCap is a recovery operating system — habits, medicines, journal triggers, craving forecasts, and a 5-phase SOS designed with clinical seriousness and human warmth.',
    hook: 'When it matters, SteadyCap is one tap from your home screen.',
    nameStory: 'Recovery is not a streak — it is staying steady, day after day. SteadyCap names that philosophy: calm progress under the Capricorn umbrella.',
    accent: '#c9652b',
    accent2: '#2f8e88',
    bg: '#1a110e',
    url: 'https://shamikhahmed.github.io/SteadyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/SteadyCap/pitch.html',
    presentationUrl: 'https://shamikhahmed.github.io/SteadyCap/presentation.html',
    privacyUrl: 'https://shamikhahmed.github.io/SteadyCap/privacy.html',
    github: 'https://github.com/shamikhahmed/SteadyCap',
    problems: [
      'Habit trackers gamify guilt — streaks break and shame follows.',
      'Recovery tools are either too clinical or too cute to trust in a crisis.',
      'Sensitive journals and medicine logs should never sync to a startup server.',
    ],
    promise: 'Pattern-aware recovery: trigger forecasts, SOS phases, medicine tracking, and milestones — warm, private, on-device.',
    features: [
      { t: 'Trigger forecast', d: 'Pattern engine surfaces risk windows from your own journal — not generic tips.' },
      { t: '5-phase SOS', d: 'Structured crisis flow when seconds matter — breathing, grounding, next step.' },
      { t: 'Medicine tracker', d: 'Schedules and adherence without cloud PHI exposure.' },
      { t: 'Journal triggers', d: 'Tag emotional patterns privately — data never leaves the device.' },
      { t: 'Habit milestones', d: 'Celebrate progress without punishing broken streaks.' },
      { t: 'Clinic warmth UX', d: 'Fraunces serif, orange/teal calm — supportive, not sterile.' },
    ],
    vs: [
      { name: 'Streak apps', note: 'Guilt mechanics — SteadyCap is built for recovery gravity.' },
      { name: 'Generic meditation', note: 'No SOS, no medicine, no trigger forecasting.' },
    ],
    personas: ['Recovery journeys', 'Structured habit rebuilders', 'Supporters who need discretion'],
    faqs: [
      { q: 'Is this medical advice?', a: 'SteadyCap is a private tool — not a replacement for professional care.' },
      { q: 'Who sees my journal?', a: 'Only you. No cloud sync.' },
      { q: 'SOS offline?', a: 'Yes — designed to work when connectivity fails.' },
    ],
    highlights: ['Trigger forecast', '5-phase SOS', 'Medicine tracker', 'Journal', 'Milestones'],
    screenshot: 'assets/screenshots/steadycap.png',
    screenshots: shotPaths('steadycap'),
    devices: deviceShotPaths('steadycap'),
    screenshotAlts: [
      'SteadyCap recovery landing page',
      'SteadyCap daily dashboard',
      'SteadyCap today overview',
      'SteadyCap recovery habits',
      'SteadyCap five-phase SOS',
      'SteadyCap knowledge library',
      'SteadyCap private journal',
      'SteadyCap profile settings',
    ],
    ux: [{'step': '01', 'icon': '🌿', 'title': 'Open SteadyCap', 'desc': 'A calm recovery OS — warm typography, no streak guilt on first load.'}, {'step': '02', 'icon': '📲', 'title': 'Install privately', 'desc': 'Home screen access when you need SOS in seconds.'}, {'step': '03', 'icon': '📓', 'title': 'Journal & track', 'desc': 'Medicines, triggers, and habits stay on your device only.'}, {'step': '04', 'icon': '🆘', 'title': 'SOS when it matters', 'desc': 'Five-phase crisis flow works offline — built for real moments.'}],
  },
  ledgercap: {
    id: 'LedgerCap',
    slug: 'ledgercap',
    legacySlug: 'stundsos',
    name: 'LedgerCap',
    category: 'Wealth',
    symbol: '▣',
    tagline: 'Pakistani wealth. One ledger.',
    pitch: 'LedgerCap is a wealth operating system for PSX stocks, Meezan funds, Zakat, IPO tracking, and net worth — Bloomberg clarity for Pakistani investors, without Bloomberg price or cloud leakage.',
    hook: 'PSX, funds, Zakat, net worth — terminal-grade, phone-native, private.',
    nameStory: 'A ledger is the honest record of what you own — the oldest tool in finance. LedgerCap brings that clarity to Pakistani wealth, with Cap for Capricorn.',
    accent: '#f59e0b',
    accent2: '#0ecb81',
    bg: '#0b0e11',
    url: 'https://shamikhahmed.github.io/LedgerCap/',
    pitchUrl: 'https://shamikhahmed.github.io/LedgerCap/pitch.html',
    presentationUrl: 'https://shamikhahmed.github.io/LedgerCap/presentation.html',
    privacyUrl: 'https://shamikhahmed.github.io/LedgerCap/privacy.html',
    github: 'https://github.com/shamikhahmed/LedgerCap',
    problems: [
      'US portfolio apps ignore PSX, Meezan funds, and PKR-native Zakat.',
      'Brokerage portals are read-only — you still spreadsheet everything manually.',
      'Wealth dashboards want API keys and cloud aggregation of your net worth.',
    ],
    promise: 'One gold terminal on your phone: holdings, transactions, IPO watch, Zakat, and net worth in PKR — sharp, offline, yours.',
    features: [
      { t: 'PSX holdings', d: 'Track equities with mono numerics and terminal dignity.' },
      { t: 'Meezan funds', d: 'Islamic fund positions alongside conventional holdings.' },
      { t: 'Zakat calculator', d: 'Wealth obligations from real numbers — not generic widgets.' },
      { t: 'IPO tracker', d: 'Watch new issues without refreshing broker sites.' },
      { t: 'Net worth PKR', d: 'Unified ledger with tabular alignment and gold-on-charcoal chrome.' },
      { t: 'Terminal identity', d: 'Barlow Condensed + JetBrains Mono — data deserves respect.' },
    ],
    vs: [
      { name: 'TradingView', note: 'Charts, not a PK wealth OS with Zakat.' },
      { name: 'US robo-advisors', note: 'Wrong market, wrong currency, cloud-dependent.' },
    ],
    personas: ['Pakistani investors', 'Fund holders', 'Anyone tracking PKR net worth privately'],
    faqs: [
      { q: 'Live market data?', a: 'LedgerCap is your private ledger — you enter holdings you own.' },
      { q: 'Multi-currency?', a: 'PKR-first with multinational context where configured.' },
      { q: 'Install', a: 'PWA — Add to Home Screen for daily terminal access.' },
    ],
    highlights: ['PSX', 'Meezan funds', 'Zakat', 'IPO tracker', 'Net worth'],
    screenshot: 'assets/screenshots/ledgercap.png',
    screenshots: shotPaths('ledgercap'),
    devices: deviceShotPaths('ledgercap'),
    screenshotAlts: [
      'LedgerCap wealth terminal landing',
      'LedgerCap PKR dashboard',
      'LedgerCap net worth terminal',
      'LedgerCap PSX portfolio',
      'LedgerCap transaction log',
      'LedgerCap income tracker',
      'LedgerCap settings panel',
      'LedgerCap holdings overview',
    ],
    ux: [{'step': '01', 'icon': '▣', 'title': 'Open the terminal', 'desc': 'Gold-on-charcoal wealth OS — PSX and PKR-native from the first screen.'}, {'step': '02', 'icon': '📲', 'title': 'Dock on home screen', 'desc': 'Daily net worth checks without opening a broker portal.'}, {'step': '03', 'icon': '📈', 'title': 'Log holdings', 'desc': 'PSX, Meezan funds, IPO watch — your ledger, your numbers.'}, {'step': '04', 'icon': '🌙', 'title': 'Calculate Zakat', 'desc': 'Obligations from real holdings — private, auditable, offline.'}],
  },
  deeponycap: {
    id: 'DeePonyCap',
    slug: 'deeponycap',
    legacySlug: 'deeponyos',
    name: 'DeePonyCap',
    category: 'Collection',
    symbol: '♡',
    tagline: 'Every pony. One stable.',
    pitch: 'DeePonyCap is a child-safe MLP collection OS — generations G1–G5, wishlists, photo shelves, and bubble stats. Playful enough for kids, powerful enough for collectors.',
    hook: 'Open the stable. No ads. No chat. No cloud.',
    nameStory: 'Dee is for the deep love kids put into their collections. Pony is the world. Cap connects a playful stable to the rest of Capricorn Systems.',
    accent: '#c4367a',
    accent2: '#8b5cf6',
    bg: '#d4a0b8',
    text: '#2d1235',
    textDim: '#5c2348',
    light: true,
    url: 'https://shamikhahmed.github.io/DeePonyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/DeePonyCap/pitch.html',
    presentationUrl: 'https://shamikhahmed.github.io/DeePonyCap/presentation.html',
    privacyUrl: 'https://shamikhahmed.github.io/DeePonyCap/privacy.html',
    github: 'https://github.com/shamikhahmed/DeePonyCap',
    problems: [
      'Collectors use spreadsheets — kids can\'t use spreadsheets.',
      'Toy apps bombard children with ads and account walls.',
      'Photo collections of shelves shouldn\'t upload to someone else\'s server.',
    ],
    promise: 'A pastel toy-shelf on your device: catalog ponies, photograph shelves, tier wishlists, earn bubbles — COPPA-minded, offline, joyful.',
    features: [
      { t: 'G1–G5 catalog', d: 'Generations organized the way collectors think — not database rows.' },
      { t: 'Photo shelves', d: 'IndexedDB photos stay on-device — their collection, their memories.' },
      { t: 'Wishlist tiers', d: 'Want, need, grail — kid-friendly priority without ecommerce dark patterns.' },
      { t: 'Achievement bubbles', d: 'Gentle gamification without streak punishment.' },
      { t: 'COPPA-safe design', d: 'No accounts, no social, no outbound data.' },
      { t: 'Toy-shelf UX', d: 'Baloo 2 + Nunito, floating pill nav — Fisher-Price meets collector catalog.' },
    ],
    vs: [
      { name: 'Spreadsheets', note: 'Adults only — DeePonyCap is built for small hands.' },
      { name: 'Generic toy apps', note: 'Ads and accounts — DeePonyCap is a private stable.' },
    ],
    personas: ['MLP collectors', 'Parents', 'Kids cataloguing their stable'],
    faqs: [
      { q: 'Age appropriate?', a: 'Designed for kids to use alone — no chat or social features.' },
      { q: 'Photos stored where?', a: 'On your device only, via IndexedDB.' },
      { q: 'Works on iPad?', a: 'Yes — responsive PWA with touch-first shelves.' },
    ],
    highlights: ['G1–G5', 'Photo shelves', 'Wishlists', 'Achievements', 'COPPA-safe'],
    screenshot: 'assets/screenshots/deeponycap.png',
    screenshots: shotPaths('deeponycap'),
    devices: deviceShotPaths('deeponycap'),
    screenshotAlts: [
      'DeePonyCap collection landing',
      'DeePonyCap stable home screen',
      'DeePonyCap pony stable overview',
      'DeePonyCap G1–G5 collection',
      'DeePonyCap wishlist tiers',
      'DeePonyCap photo shelves',
      'DeePonyCap bubble stats',
      'DeePonyCap settings panel',
    ],
    ux: [{'step': '01', 'icon': '♡', 'title': 'Open the stable', 'desc': 'Pastel shelves and bubble stats — kid-friendly from the first tap.'}, {'step': '02', 'icon': '📲', 'title': 'Add to iPad home', 'desc': 'Touch-first PWA perfect for cataloguing on the floor.'}, {'step': '03', 'icon': '📸', 'title': 'Photo your shelves', 'desc': 'IndexedDB keeps pony photos on-device — never uploaded.'}, {'step': '04', 'icon': '⭐', 'title': 'Collect & wishlist', 'desc': 'G1–G5 catalog, tiers, and gentle achievements without ads.'}],
  },
  scentcap: {
    id: 'ScentCap',
    slug: 'scentcap',
    name: 'ScentCap',
    category: 'Lifestyle',
    ver: '1.0.0',
    symbol: '◌',
    tagline: 'Your fragrance operating system.',
    pitch: 'ScentCap is a fragrance wardrobe OS — daily advisor, weather-aware picks, layering lab, wear calendar, and rotation analytics. Warm amber chrome for collectors who refuse cloud beauty apps.',
    hook: 'Wardrobe. Advisor. Layering. Calendar. All offline.',
    nameStory: 'Scent is what you wear. Cap marks it as a standalone Cap app — same sovereignty standard as Capricorn, built for fragrance life.',
    accent: '#c9a87c',
    accent2: '#8b6914',
    bg: '#1a1614',
    url: 'https://shamikhahmed.github.io/ScentCap/',
    pitchUrl: 'https://shamikhahmed.github.io/ScentCap/pitch.html',
    presentationUrl: 'https://shamikhahmed.github.io/ScentCap/presentation.html',
    privacyUrl: 'https://shamikhahmed.github.io/ScentCap/privacy.html',
    github: 'https://github.com/shamikhahmed/ScentCap',
    problems: [
      'Fragrance collectors track bottles in notes apps — no levels, wear history, or rotation health.',
      'Weather and occasion should shape daily picks — but spreadsheets cannot advise.',
      'Beauty apps want accounts, ads, and scent profiles uploaded to their cloud.',
    ],
    promise: 'One amber wardrobe on your phone: catalog bottles, get Smart Advisor picks, log wears, layer with confidence — private, offline, yours.',
    features: [
      { t: 'Today dashboard', d: 'Weather context, daily advisor score, occasion presets, one-tap wear logging.' },
      { t: 'Wardrobe catalog', d: 'Search seed database, track bottle levels, favorites, and signature scent.' },
      { t: 'Smart Advisor', d: 'Rules-based picks for office, dates, weekends, galas — no external API.' },
      { t: 'Layering Lab', d: 'Save base + top combos that work on your skin chemistry.' },
      { t: 'Calendar & analytics', d: 'Wear heatmap, rotation health, family breakdown charts.' },
      { t: 'Warm amber UX', d: 'Mist gradients, gold accents — perfumery calm, not beauty-app neon.' },
    ],
    vs: [
      { name: 'Notes / spreadsheets', note: 'No advisor, no weather, no wear tracking.' },
      { name: 'Cloud beauty apps', note: 'Accounts and data harvesting — ScentCap is local-only.' },
    ],
    personas: ['Fragrance collectors', 'Office professionals', 'Travelers packing decants'],
    faqs: [
      { q: 'Does ScentCap need the internet?', a: 'After first load it runs offline. Optional Open-Meteo weather when you grant location.' },
      { q: 'Is the advisor AI?', a: 'Smart Assistant — rules-based logic on your profile and weather. No LLM.' },
      { q: 'How do I try it?', a: 'Onboarding offers demo mode with 12 bottles and 30 days of wear history.' },
    ],
    highlights: ['Wardrobe', 'Smart Advisor', 'Layering', 'Calendar', 'Offline PWA'],
    screenshot: 'assets/screenshots/scentcap.png',
    screenshots: shotPaths('scentcap'),
    devices: deviceShotPaths('scentcap'),
    screenshotAlts: [
      'ScentCap fragrance landing page',
      'ScentCap Today home dashboard',
      'ScentCap daily advisor pick',
      'ScentCap wardrobe collection',
      'ScentCap Smart Advisor screen',
      'ScentCap layering lab',
      'ScentCap wear calendar',
      'ScentCap analytics overview',
    ],
    ux: [{'step': '01', 'icon': '💧', 'title': 'Open ScentCap', 'desc': 'Warm amber fragrance OS — demo wardrobe loads in one tap.'}, {'step': '02', 'icon': '📲', 'title': 'Add to Home Screen', 'desc': 'Daily wear picks one tap from your lock screen.'}, {'step': '03', 'icon': '✨', 'title': 'Build wardrobe', 'desc': 'Search seed DB, track levels, mark signature scent.'}, {'step': '04', 'icon': '📅', 'title': 'Track & refine', 'desc': 'Log wears, layer combos, watch rotation health — all on-device.'}],
  },
  auracap: {
    id: 'AuraCap',
    slug: 'auracap',
    name: 'AuraCap',
    category: 'Productivity',
    ver: '5.0.0',
    symbol: '◎',
    tagline: 'Every device. Perfected.',
    pitch: 'AuraCap is an Apple Ecosystem Studio — 16 modules for Digital DNA, smart folders, wallpapers, widgets, lockscreens, and rules-based design. Import your real app list and organize iPhone, iPad, and Mac offline.',
    hook: 'Aura Score. DNA. Import. Design. Zero cloud.',
    nameStory: 'Aura is the glow around a perfected setup. Cap ties it to the Cap portfolio — sovereign software for Apple power users.',
    accent: '#4f6ef7',
    accent2: '#7b5ea7',
    bg: '#050507',
    url: 'https://shamikhahmed.github.io/AuraCap/',
    pitchUrl: 'https://shamikhahmed.github.io/AuraCap/pitch.html',
    presentationUrl: 'https://shamikhahmed.github.io/AuraCap/presentation.html',
    privacyUrl: 'https://shamikhahmed.github.io/AuraCap/privacy.html',
    github: 'https://github.com/shamikhahmed/AuraCap',
    problems: [
      '200 apps across iPhone, iPad, Mac — no single DNA view of your digital wardrobe.',
      'Getting your real app list into a planner requires manual Shortcuts or Terminal hacks.',
      'Wallpapers, widgets, and lockscreens are designed in separate apps that phone home.',
    ],
    promise: 'One blue-purple studio: import apps, analyze DNA, score your Aura, design layouts across three devices — offline, private, command-palette fast.',
    features: [
      { t: '16 modules', d: 'Dashboard, DNA, Import, App Library, Organizer, Designer, Wallpapers, Widgets, and more.' },
      { t: 'Digital DNA', d: 'Rules-based app personality analysis — productivity, social, finance patterns.' },
      { t: 'Import flows', d: 'iOS Shortcuts, Mac Terminal, paste .txt, App Library 1000+, demo mode.' },
      { t: 'Aura Score', d: 'Holistic ecosystem health from your real imported wardrobe.' },
      { t: 'Design studio', d: '42+ wallpapers, lockscreen builder, widget lab, 12 shortcuts.' },
      { t: 'Glass chrome UX', d: 'Blue-purple gradients, device previews — Apple-native energy.' },
    ],
    vs: [
      { name: 'Screenshot mood boards', note: 'Static images — AuraCap analyzes your real app list.' },
      { name: 'Cloud planners', note: 'Upload your apps to their server — AuraCap stays local.' },
    ],
    personas: ['Multi-device Apple users', 'Customization enthusiasts', 'Productivity power users'],
    faqs: [
      { q: 'How do I import apps?', a: 'iOS Shortcuts, Mac Terminal, paste .txt, or browse App Library. Full guide in-app.' },
      { q: 'Is AI Designer real AI?', a: 'Smart Assistant — rules-based layout recommendations. No external LLM.' },
      { q: 'Works offline?', a: 'Yes — full PWA after first load with IndexedDB persistence.' },
    ],
    highlights: ['16 modules', 'Digital DNA', 'Aura Score', 'Import guide', 'Offline PWA'],
    screenshot: 'assets/screenshots/auracap.png',
    screenshots: shotPaths('auracap'),
    devices: deviceShotPaths('auracap'),
    screenshotAlts: [
      'AuraCap ecosystem studio landing',
      'AuraCap dashboard control center',
      'AuraCap Aura Score overview',
      'AuraCap Digital DNA analysis',
      'AuraCap import apps screen',
      'AuraCap smart organizer',
      'AuraCap AI designer layouts',
      'AuraCap wallpaper gallery',
    ],
    ux: [{'step': '01', 'icon': '◎', 'title': 'Launch studio', 'desc': 'Blue-purple ecosystem OS — demo wardrobe or import your apps.'}, {'step': '02', 'icon': '📲', 'title': 'Install privately', 'desc': 'Home screen access with ⌘K command palette.'}, {'step': '03', 'icon': '🧬', 'title': 'Analyze DNA', 'desc': 'Aura Score and smart folders from your real app list.'}, {'step': '04', 'icon': '🎨', 'title': 'Design layouts', 'desc': 'Wallpapers, widgets, lockscreens — all stored on-device.'}],
  },
};

const PRODUCTS_LIST = Object.values(PRODUCTS);

const LEGACY_SLUG_MAP = Object.fromEntries(
  Object.values(PRODUCTS).map((p) => [p.legacySlug, p.slug])
);

const COMPANY = {
  founder: { name: 'Shamikh Ahmed', title: 'Founder & CEO' },
  sovereignty: {
    title: 'Device Sovereignty',
    subtitle: 'The one rule every Capricorn product shares',
    points: [
      'Your data stays on your device — not on our servers',
      'Works offline after first load — no mandatory account',
      'You own the vault, the workouts, the games, the ledger',
    ],
  },
};
