/* Capricorn Systems — product catalog */
const CAPRICORN = {
  name: 'Capricorn Systems',
  tagline: 'Software that lives on your device — not in our cloud.',
  sub: 'Premium personal software for finance, health, play, recovery, wealth, and life.',
};

const PRODUCTS = {
  vaultcap: {
    id: 'VaultCap',
    slug: 'vaultcap',
    legacySlug: 'vaultos',
    name: 'VaultCap',
    category: 'Finance & Identity',
    ver: '4.1.0',
    symbol: '◆',
    tagline: 'Your encrypted life vault.',
    pitch: 'VaultCap is a zero-knowledge life operating system for finance, identity, and documents — built for multinational families who refuse to rent their privacy from a cloud.',
    hook: 'Bank-grade encryption. No server. No account. No subscription drama.',
    accent: '#5b8dee',
    accent2: '#3d5a9e',
    bg: '#070b14',
    url: 'https://shamikhahmed.github.io/VaultCap/',
    pitchUrl: 'https://shamikhahmed.github.io/VaultCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/VaultCap/privacy.html',
    github: 'https://github.com/shamikhahmed/VaultCap',
    problems: [
      'Budget apps want your bank logins and sell insight graphs back to advertisers.',
      'Password managers and finance tools live in separate silos — and both phone home.',
      'Diaspora families juggle PK, UK, and UAE money with no single private ledger.',
    ],
    promise: 'One vault on your phone: net worth, documents, family profiles, Zakat, and 120+ banks — encrypted before it ever touches storage.',
    features: [
      { t: 'AES-256-GCM vault', d: 'Military-grade encryption with PBKDF2 310k iterations. Your PIN never leaves the device.' },
      { t: '120+ banks', d: 'Pakistan, UK, and UAE institutions with smart import — offline parsing, no Plaid dependency.' },
      { t: 'Family vault', d: 'Separate profiles with guided demo, personal default, and premium recovery you control.' },
      { t: 'Zakat engine', d: 'Islamic wealth obligations calculated from your real holdings — private, auditable, on-device.' },
      { t: 'Smart Import', d: 'Drop statements and screenshots; VaultCap structures them without uploading anywhere.' },
      { t: 'Swiss-vault UX', d: 'IBM Plex Mono numerics, indigo grid chrome — calm authority, not fintech neon.' },
    ],
    vs: [
      { name: 'Mint / YNAB', note: 'Cloud-first, account-required, data is the product.' },
      { name: '1Password', note: 'Secrets only — no net worth, Zakat, or family finance OS.' },
    ],
    personas: ['Privacy-conscious professionals', 'Multinational families', 'Diaspora managing PK + UK finances'],
    faqs: [
      { q: 'Does VaultCap need the internet?', a: 'After first load it runs offline. No mandatory sync or account.' },
      { q: 'Can you see my data?', a: 'No. Zero-knowledge design — encryption happens on your device.' },
      { q: 'How do I install?', a: 'Open the app in Safari/Chrome → Share → Add to Home Screen for a full-screen vault.' },
    ],
    highlights: ['AES-256-GCM', '120+ banks', 'Family vault', 'Zakat engine', 'Smart Import'],
  },
  pulsecap: {
    id: 'PulseCap',
    slug: 'pulsecap',
    legacySlug: 'fitnessos',
    name: 'PulseCap',
    category: 'Performance',
    symbol: '◇',
    tagline: 'Train smarter. Recover harder.',
    pitch: 'PulseCap is a performance operating system with 300+ exercises, body intelligence, Smart Coach, and recovery science — for lifters who want Whoop-grade insight without a hardware lock-in.',
    hook: 'Your pulse, your PRs, your program — kinetic, offline, yours.',
    accent: '#00f2ff',
    accent2: '#0e7bff',
    bg: '#0a0a0f',
    url: 'https://shamikhahmed.github.io/PulseCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PulseCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/PulseCap/privacy.html',
    github: 'https://github.com/shamikhahmed/PulseCap',
    problems: [
      'Workout apps nag you to subscribe before you can log a single set.',
      'Training and recovery live in different apps that never talk — unless you pay for both.',
      'Cloud fitness products leak habits, locations, and body data you never agreed to share.',
    ],
    promise: 'One kinetic dashboard: training, body map, readiness, PRs, and rule-based Smart Coach — no cloud, no wearable tax.',
    features: [
      { t: '300+ exercises', d: 'Full library with muscle mapping and session logging built for serious training.' },
      { t: 'Body map', d: 'Measurements and visual body intelligence — track composition changes privately.' },
      { t: 'Smart Coach', d: 'Offline rule engine that adapts volume and recovery cues from your actual history.' },
      { t: 'Recovery readiness', d: 'Readiness signals without selling your sleep to a subscription dashboard.' },
      { t: 'PR tracking', d: 'Tabular numerics, angular chrome — every rep counted with athletic precision.' },
      { t: 'Kinetic identity', d: 'Rajdhani + Sora, electric cyan stripes — feels like a training lab, not a logger.' },
    ],
    vs: [
      { name: 'Strong / Hevy', note: 'Great loggers — but cloud accounts and no recovery OS layer.' },
      { name: 'Whoop', note: 'Hardware subscription — PulseCap is software sovereignty on your phone.' },
    ],
    personas: ['Serious lifters', 'Home gym athletes', 'Coaches who need offline reliability'],
    faqs: [
      { q: 'Do I need a wearable?', a: 'No. PulseCap works from your training data and manual inputs.' },
      { q: 'Works offline?', a: 'Yes — full PWA after first load.' },
      { q: 'Install tip', a: 'Add to Home Screen on iPhone for the best full-screen training experience.' },
    ],
    highlights: ['300+ exercises', 'Body map', 'Smart Coach', 'Recovery', 'PR tracking'],
  },
  prismcap: {
    id: 'PrismCap',
    slug: 'prismcap',
    legacySlug: 'prismos',
    name: 'PrismCap',
    category: 'Play',
    symbol: '✦',
    tagline: '38 games. One phone. Zero Wi‑Fi.',
    pitch: 'PrismCap is a holographic party arcade — pass-and-play games, achievements, daily challenges, and couch multiplayer with no accounts, no ads, and no internet required.',
    hook: 'The living room becomes an arcade. Pass the phone, not your data.',
    accent: '#c77dff',
    accent2: '#ff2d78',
    bg: '#0a0014',
    url: 'https://shamikhahmed.github.io/PrismCap/',
    pitchUrl: 'https://shamikhahmed.github.io/PrismCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/PrismCap/privacy.html',
    github: 'https://github.com/shamikhahmed/PrismCap',
    problems: [
      'Mobile games demand accounts, loot boxes, and constant connectivity.',
      'Board game nights need setup, pieces, and rules nobody remembers.',
      'Party apps harvest contacts and microphone data for "social features."',
    ],
    promise: 'Install once — 38 engineered games, XP, achievements, and pass-and-play chaos that works in airplane mode.',
    features: [
      { t: '38 game engines', d: 'Deduction, reflex, strategy, party — each with its own drama and haptics.' },
      { t: 'Pass & Play', d: 'Built for the couch: pass the device, reveal roles, betray friends — privately.' },
      { t: 'Daily challenges', d: 'Fresh goals without server pings or push-notification spam.' },
      { t: 'XP + achievements', d: 'Progress stays on your device — your arcade, your legend.' },
      { t: 'QR state transfer', d: 'Move sessions between phones without cloud accounts.' },
      { t: 'Neon arcade chrome', d: 'Audiowide display, magenta glass — Jackbox energy, Apple polish.' },
    ],
    vs: [
      { name: 'Jackbox', note: 'Paid packs + TV setup — PrismCap is 38 games in one phone install.' },
      { name: 'App Store party games', note: 'Ads, accounts, and data harvesting — PrismCap is offline-first.' },
    ],
    personas: ['Families', 'Friend groups', 'Dorm rooms', 'Anyone who wants instant offline fun'],
    faqs: [
      { q: 'Internet required?', a: 'No — after first load, PrismCap is fully offline.' },
      { q: 'How many players?', a: 'Most games support pass-and-play groups; check each game card.' },
      { q: 'Kids safe?', a: 'No accounts, no chat servers, no ads — local play only.' },
    ],
    highlights: ['38 games', 'Pass & Play', 'Daily challenges', 'XP system', 'Offline audio'],
  },
  steadycap: {
    id: 'SteadyCap',
    slug: 'steadycap',
    legacySlug: 'disciplineos',
    name: 'SteadyCap',
    category: 'Recovery',
    symbol: '○',
    tagline: 'Recovery is a system. Not a streak.',
    pitch: 'SteadyCap is a recovery operating system — habits, medicines, journal triggers, craving forecasts, and a 5-phase SOS designed with clinical seriousness and human warmth.',
    hook: 'When it matters, SteadyCap is one tap from your home screen.',
    accent: '#c9652b',
    accent2: '#2f8e88',
    bg: '#1a110e',
    url: 'https://shamikhahmed.github.io/SteadyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/SteadyCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/SteadyCap/privacy.html',
    github: 'https://github.com/shamikhahmed/SteadyCap',
    problems: [
      'Habit trackers gamify guilt — streaks break and shame follows.',
      'Recovery tools are either too clinical or too cute to trust in a crisis.',
      'Sensitive journals and medicine logs should never sync to a startup server.',
    ],
    promise: 'Pattern-aware recovery: trigger forecasts, SOS phases, medicine tracking, and milestones — warm, private, on-device.',
    features: [
      { t: 'Trigger forecast', d: 'Pattern engine surfaces risk windows from your own journal — not generic tips.' },
      { t: '5-phase SOS', d: 'Structured crisis flow when seconds matter — breathing, grounding, next step.' },
      { t: 'Medicine tracker', d: 'Schedules and adherence without cloud PHI exposure.' },
      { t: 'Journal triggers', d: 'Tag emotional patterns privately — data never leaves the device.' },
      { t: 'Habit milestones', d: 'Celebrate progress without punishing broken streaks.' },
      { t: 'Clinic warmth UX', d: 'Fraunces serif, orange/teal calm — supportive, not sterile.' },
    ],
    vs: [
      { name: 'Streak apps', note: 'Guilt mechanics — SteadyCap is built for recovery gravity.' },
      { name: 'Generic meditation', note: 'No SOS, no medicine, no trigger forecasting.' },
    ],
    personas: ['Recovery journeys', 'Structured habit rebuilders', 'Supporters who need discretion'],
    faqs: [
      { q: 'Is this medical advice?', a: 'SteadyCap is a private tool — not a replacement for professional care.' },
      { q: 'Who sees my journal?', a: 'Only you. No cloud sync.' },
      { q: 'SOS offline?', a: 'Yes — designed to work when connectivity fails.' },
    ],
    highlights: ['Trigger forecast', '5-phase SOS', 'Medicine tracker', 'Journal', 'Milestones'],
  },
  ledgercap: {
    id: 'LedgerCap',
    slug: 'ledgercap',
    legacySlug: 'stundsos',
    name: 'LedgerCap',
    category: 'Wealth',
    symbol: '▣',
    tagline: 'Pakistani wealth. One ledger.',
    pitch: 'LedgerCap is a wealth operating system for PSX stocks, Meezan funds, Zakat, IPO tracking, and net worth — Bloomberg clarity for Pakistani investors, without Bloomberg price or cloud leakage.',
    hook: 'PSX, funds, Zakat, net worth — terminal-grade, phone-native, private.',
    accent: '#f59e0b',
    accent2: '#0ecb81',
    bg: '#0b0e11',
    url: 'https://shamikhahmed.github.io/LedgerCap/',
    pitchUrl: 'https://shamikhahmed.github.io/LedgerCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/LedgerCap/privacy.html',
    github: 'https://github.com/shamikhahmed/LedgerCap',
    problems: [
      'US portfolio apps ignore PSX, Meezan funds, and PKR-native Zakat.',
      'Brokerage portals are read-only — you still spreadsheet everything manually.',
      'Wealth dashboards want API keys and cloud aggregation of your net worth.',
    ],
    promise: 'One gold terminal on your phone: holdings, transactions, IPO watch, Zakat, and net worth in PKR — sharp, offline, yours.',
    features: [
      { t: 'PSX holdings', d: 'Track equities with mono numerics and terminal dignity.' },
      { t: 'Meezan funds', d: 'Islamic fund positions alongside conventional holdings.' },
      { t: 'Zakat calculator', d: 'Wealth obligations from real numbers — not generic widgets.' },
      { t: 'IPO tracker', d: 'Watch new issues without refreshing broker sites.' },
      { t: 'Net worth PKR', d: 'Unified ledger with tabular alignment and gold-on-charcoal chrome.' },
      { t: 'Terminal identity', d: 'Barlow Condensed + JetBrains Mono — data deserves respect.' },
    ],
    vs: [
      { name: 'TradingView', note: 'Charts, not a PK wealth OS with Zakat.' },
      { name: 'US robo-advisors', note: 'Wrong market, wrong currency, cloud-dependent.' },
    ],
    personas: ['Pakistani investors', 'Fund holders', 'Anyone tracking PKR net worth privately'],
    faqs: [
      { q: 'Live market data?', a: 'LedgerCap is your private ledger — you enter holdings you own.' },
      { q: 'Multi-currency?', a: 'PKR-first with multinational context where configured.' },
      { q: 'Install', a: 'PWA — Add to Home Screen for daily terminal access.' },
    ],
    highlights: ['PSX', 'Meezan funds', 'Zakat', 'IPO tracker', 'Net worth'],
  },
  deeponycap: {
    id: 'DeePonyCap',
    slug: 'deeponycap',
    legacySlug: 'deeponyos',
    name: 'DeePonyCap',
    category: 'Collection',
    symbol: '♡',
    tagline: 'Every pony. One stable.',
    pitch: 'DeePonyCap is a child-safe MLP collection OS — generations G1–G5, wishlists, photo shelves, and bubble stats. Playful enough for kids, powerful enough for collectors.',
    hook: 'Open the stable. No ads. No chat. No cloud.',
    accent: '#f472b6',
    accent2: '#a78bfa',
    bg: '#fff1fa',
    light: true,
    url: 'https://shamikhahmed.github.io/DeePonyCap/',
    pitchUrl: 'https://shamikhahmed.github.io/DeePonyCap/pitch.html',
    privacyUrl: 'https://shamikhahmed.github.io/DeePonyCap/privacy.html',
    github: 'https://github.com/shamikhahmed/DeePonyCap',
    problems: [
      'Collectors use spreadsheets — kids can\'t use spreadsheets.',
      'Toy apps bombard children with ads and account walls.',
      'Photo collections of shelves shouldn\'t upload to someone else\'s server.',
    ],
    promise: 'A pastel toy-shelf on your device: catalog ponies, photograph shelves, tier wishlists, earn bubbles — COPPA-minded, offline, joyful.',
    features: [
      { t: 'G1–G5 catalog', d: 'Generations organized the way collectors think — not database rows.' },
      { t: 'Photo shelves', d: 'IndexedDB photos stay on-device — their collection, their memories.' },
      { t: 'Wishlist tiers', d: 'Want, need, grail — kid-friendly priority without ecommerce dark patterns.' },
      { t: 'Achievement bubbles', d: 'Gentle gamification without streak punishment.' },
      { t: 'COPPA-safe design', d: 'No accounts, no social, no outbound data.' },
      { t: 'Toy-shelf UX', d: 'Baloo 2 + Nunito, floating pill nav — Fisher-Price meets collector catalog.' },
    ],
    vs: [
      { name: 'Spreadsheets', note: 'Adults only — DeePonyCap is built for small hands.' },
      { name: 'Generic toy apps', note: 'Ads and accounts — DeePonyCap is a private stable.' },
    ],
    personas: ['MLP collectors', 'Parents', 'Kids cataloguing their stable'],
    faqs: [
      { q: 'Age appropriate?', a: 'Designed for kids to use alone — no chat or social features.' },
      { q: 'Photos stored where?', a: 'On your device only, via IndexedDB.' },
      { q: 'Works on iPad?', a: 'Yes — responsive PWA with touch-first shelves.' },
    ],
    highlights: ['G1–G5', 'Photo shelves', 'Wishlists', 'Achievements', 'COPPA-safe'],
  },
};

const PRODUCTS_LIST = Object.values(PRODUCTS);

const LEGACY_SLUG_MAP = Object.fromEntries(
  Object.values(PRODUCTS).map((p) => [p.legacySlug, p.slug])
);

const COMPANY = {
  founder: { name: 'Shamikh Ahmed', title: 'Founder & CEO' },
  sovereignty: {
    title: 'Device Sovereignty',
    subtitle: 'The one rule every Capricorn product shares',
    points: [
      'Your data stays on your device — not on our servers',
      'Works offline after first load — no mandatory account',
      'You own the vault, the workouts, the games, the ledger',
    ],
  },
};
